apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  type: ClusterIP
  externalTrafficPolicy: null
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: envoy
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
      - name: envoy
        ports:
        - containerPort: 80
          hostPort: null
        - containerPort: 443
          hostPort: null
